baseurl = "/"
languageCode = "en-US"
title = "My Website"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/post/:year/:month/:day/:slug"

[params]
  avatar = "profile1.png"
  author = "Kapil Mangrolia"
  occupation = "Mechanical Engineering Student"
  about = "Passionate for design, programming, and computational simulation"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "kapilmangrolia"
  Email         = "kapil.mangrolia@gmail.com"
#  Twitter       = "username"
  LinkedIn      = "kapil-mangrolia-494049153"
#  Instagram     = "username"
#  Stackoverflow = "username"
#  Medium        = "username"
#  Telegram      = "username"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/post/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
